### ISSUE TITLE
Can't work with Spatial Interpolation

### ISSUE THREAD

**Issue by BrownBichon** [Smallpath/Memory#12]
I modified the shape of the `position` path, saved the layer as a new item. Then I clicked the item to re-create the layer, my modification of the path didn't show up, although the preview is working well.

- Before:
![before](https://cloud.githubusercontent.com/assets/10085220/15992715/1ed11096-3105-11e6-9d4b-912d73e4342e.JPG)

- After
![after](https://cloud.githubusercontent.com/assets/10085220/15992716/222e1496-3105-11e6-8f11-fb086c50c956.JPG)

**Comment by Smallpath** [comment]
It seems that refactor process broke the Interpolation . I will fix this immediately

**Comment by Smallpath** [comment]
Hi  BrownBichon:
  I fixed the problem you reported a few minutes ago.  
You can download the latest [jsxbin](https://raw.githubusercontent.com/Smallpath/Memory/master/Sp_memory.jsxbin) or if you use source code of Memory rather than a compiled jsxbin, just download the [AfterEffectsLayer](https://github.com/Smallpath/Memory/blob/master/Sp_memory/lib/AfterEffectsLayer.jsx) and put it into the `Sp_memory/lib` folder

**Comment by BrownBichon** [comment]
Lightning Fast! Thanks for your hard work.
